-- Seed de DESENVOLVIMENTO — espelha o conteúdo real do frontend (Next.js).
-- Fontes: src/lib/solutions-data.ts, products-data.ts, blog-data.ts, vendor-logos.ts, layout/navbar/data.ts
-- Idempotente: ON CONFLICT no slug (coluna única) / NOT EXISTS evita duplicar a cada startup.
-- Roda após o Hibernate criar o schema (spring.jpa.defer-datasource-initialization=true).
-- Antes de produção, desabilitar via spring.sql.init.mode=never ou mover para um profile de dev.

-- Limpeza de desenvolvimento para garantir re-seeding correto com novos campos e relacionamentos
ALTER TABLE conteudos ADD COLUMN IF NOT EXISTS destaque BOOLEAN DEFAULT FALSE;

DELETE FROM leads;
DELETE FROM conteudos;
DELETE FROM produto_servico;
DELETE FROM produtos;
DELETE FROM solucoes_fabricantes;
DELETE FROM solucoes;
DELETE FROM categorias;
DELETE FROM fabricantes;

-- ========== Fabricantes (vendor-logos.ts + navbar/data.ts) ==========
INSERT INTO fabricantes (id, slug, nome, descricao, descricao_curta, logo_url, site_oficial, destaque, ordem, ativo, created_at, updated_at)
VALUES
  (gen_random_uuid(), 'ibm', 'IBM', 'Servidores Power, storage corporativo, segurança de dados e IA com watsonx.', 'Servidores, storage e segurança', 'https://infodive.com.br/logos/ibm.svg', 'https://www.ibm.com', true, 1, true, now(), now()),
  (gen_random_uuid(), 'lenovo', 'Lenovo', 'Servidores ThinkSystem, hiperconvergência ThinkAgile e endpoints corporativos.', 'Endpoints e infraestrutura', 'https://infodive.com.br/logos/lenovo.svg', 'https://www.lenovo.com', true, 2, true, now(), now()),
  (gen_random_uuid(), 'dell', 'Dell Technologies', 'Servidores PowerEdge, armazenamento e infraestrutura para datacenter.', 'Servidores e armazenamento', 'https://infodive.com.br/logos/dell.svg', 'https://www.dell.com', true, 3, true, now(), now()),
  (gen_random_uuid(), 'hpe', 'HPE', 'Infraestrutura enterprise, servidores e soluções de datacenter.', 'Infraestrutura enterprise', 'https://infodive.com.br/logos/hpe.svg', 'https://www.hpe.com', true, 4, true, now(), now()),
  (gen_random_uuid(), 'veeam', 'Veeam', 'Backup, replicação e proteção de dados para ambientes híbridos e multicloud.', 'Proteção e recuperação de dados', 'https://infodive.com.br/logos/veeam.svg', 'https://www.veeam.com', true, 5, true, now(), now()),
  (gen_random_uuid(), 'acronis', 'Acronis', 'Backup e cibersegurança unificados com proteção anti-ransomware.', 'Backup e cibersegurança', 'https://infodive.com.br/logos/acronis.svg', 'https://www.acronis.com', true, 6, true, now(), now()),
  (gen_random_uuid(), 'vmware', 'VMware', 'Virtualização, hiperconvergência e nuvem privada.', 'Virtualização e nuvem privada', 'https://infodive.com.br/logos/vmware.svg', 'https://www.vmware.com', true, 7, true, now(), now()),
  (gen_random_uuid(), 'red-hat', 'Red Hat', 'Plataformas open source, Kubernetes (OpenShift) e automação enterprise.', 'Open source e Kubernetes', 'https://infodive.com.br/logos/red-hat.svg', 'https://www.redhat.com', true, 8, true, now(), now()),
  (gen_random_uuid(), 'microsoft', 'Microsoft', 'Nuvem Azure, Microsoft 365, segurança e gestão de endpoints.', 'Cloud, segurança e endpoints', 'https://infodive.com.br/logos/microsoft.svg', 'https://www.microsoft.com', true, 9, true, now(), now()),
  (gen_random_uuid(), 'aws', 'AWS', 'Nuvem pública, serviços gerenciados e infraestrutura elástica.', 'Nuvem pública e serviços gerenciados', 'https://infodive.com.br/logos/aws.svg', 'https://aws.amazon.com', true, 10, true, now(), now()),
  (gen_random_uuid(), 'suse', 'SUSE', 'Linux enterprise, Kubernetes e edge computing.', 'Linux enterprise e Kubernetes', 'https://infodive.com.br/logos/suse.svg', 'https://www.suse.com', false, 11, true, now(), now()),
  (gen_random_uuid(), 'virtuozzo', 'Virtuozzo', 'Virtualização, containers e infraestrutura de nuvem.', 'Virtualização e nuvem', 'https://infodive.com.br/logos/virtuozzo.svg', 'https://www.virtuozzo.com', false, 12, true, now(), now()),
  (gen_random_uuid(), 'apple', 'Apple', 'Dispositivos e endpoints corporativos integrados à gestão de TI.', 'Dispositivos e endpoints', 'https://infodive.com.br/logos/apple.svg', 'https://www.apple.com', false, 13, true, now(), now())
ON CONFLICT (slug) DO NOTHING;

-- ========== Categorias (Tags para Produtos e Soluções) ==========
INSERT INTO categorias (id, nome, slug, ordem, ativo, created_at, updated_at)
VALUES
  ('c1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c', 'Segurança', 'seguranca', 1, true, now(), now()),
  ('c1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6d', 'Infraestrutura', 'infraestrutura', 2, true, now(), now()),
  ('c1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6e', 'Proteção de Dados', 'backup-e-recuperacao', 3, true, now(), now()),
  ('c1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6f', 'Cloud', 'cloud', 4, true, now(), now()),
  ('c1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b7a', 'Inteligência Artificial', 'ia', 5, true, now(), now()),
  ('c1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b7b', 'Serviços', 'servicos', 6, true, now(), now())
ON CONFLICT (slug) DO NOTHING;

-- ========== Soluções (solutions-data.ts) — consumidas como "categorias" pelo frontend ==========
INSERT INTO solucoes (id, slug, titulo, icone, subtitulo_curto, descricao_curta, overview, features, imagem_url, fabricantes_titulo, fabricantes_descricao, ordem, ativo, categoria_id, created_at, updated_at)
VALUES
  (gen_random_uuid(), 'infraestrutura', 'Infraestrutura de TI Corporativa', 'server', 'Servidores robustos, redes resilientes e soluções de datacenter sob medida.', 'Sustente suas operações mais críticas com hardware de altíssima performance, escalabilidade nativa e arquitetura dedicada.', 'Nossa especialidade é projetar e implantar ambientes de hardware de alta densidade que não podem parar. Ajudamos empresas a dimensionar servidores locais e híbridos, otimizar roteamento de redes enterprise e gerenciar datacenters com foco em baixíssima latência e redundância física completa.', '[{"titulo":"Servidores Dedicados de Alta Densidade","descricao":"Processamento maciço com servidores de última geração (como Dell PowerEdge e Lenovo ThinkSystem), configurados sob medida para o ERP e bases de dados do seu negócio."},{"titulo":"Arquitetura de Rede Enterprise","descricao":"Switches de baixa latência, roteamento inteligente e firewalls integrados para garantir tráfego interno ultraveloz e seguro."},{"titulo":"Gestão e Sustentação Avançada","descricao":"Suporte especializado nível 3 constante, monitoramento de integridade física e substituição preventiva de componentes."}]'::jsonb, 'https://infodive.com.br/img/solucoes/infraestrutura.jpg', 'Fabricantes homologados', 'Trabalhamos com Dell Technologies, Lenovo e HPE.', 1, true, (SELECT id FROM categorias WHERE slug = 'infraestrutura'), now(), now()),
  (gen_random_uuid(), 'armazenamento', 'Armazenamento & Storages Corporativos', 'hard-drive', 'Storage corporativo escalável, seguro e de ultra-performance.', 'Gerencie volumes massivos de dados com storages híbridos ou 100% Flash com taxas de transferência líderes de mercado.', 'Os dados são o ativo mais precioso das corporações. Projetamos sistemas de storage escaláveis (SAN, NAS e Object Storage) com deduplicação e compressão de hardware ativas, reduzindo o custo total de propriedade (TCO) enquanto entregamos os menores tempos de acesso possíveis.', '[{"titulo":"All-Flash & Storages Híbridos","descricao":"Aceleração de leitura e escrita com storages de alto desempenho para virtualização e analytics pesado."},{"titulo":"Tiering Inteligente & FinOps","descricao":"Movimentação automática de dados frios para camadas de armazenamento econômicas ou nuvem, otimizando o TCO."},{"titulo":"Deduplicação por Hardware","descricao":"Compactação em nível de bloco que maximiza o aproveitamento físico dos storages sem degradar a performance das aplicações."}]'::jsonb, 'https://infodive.com.br/img/solucoes/armazenamento.jpg', 'Fabricantes homologados', 'Trabalhamos com IBM, Dell Technologies e Lenovo.', 2, true, (SELECT id FROM categorias WHERE slug = 'infraestrutura'), now(), now()),
  (gen_random_uuid(), 'protecao-de-dados', 'Proteção de Dados & Backup Imutável', 'shield-check', 'Sistemas avançados de backup, replicação e recuperação a prova de falhas.', 'Rotinas automáticas e criptografia militar para garantir que sua empresa possa restaurar operações críticas em minutos.', 'Protegemos a continuidade de negócios através de arquiteturas modernas de backup. Criamos ambientes imutáveis contra ataques de ransomware (WORM) e desenhamos estratégias de replicação geográfica e Disaster Recovery as a Service (DRaaS) com tempos de recuperação quase instantâneos.', '[{"titulo":"Backup Imutável (Anti-Ransomware)","descricao":"Gravação sob protocolo WORM (Write Once, Read Many). Mesmo se credenciais de administrador forem roubadas, o backup não pode ser apagado ou criptografado."},{"titulo":"Replicação Híbrida Automática","descricao":"Replicamos os dados no tripé local, nuvem privada Infodive e hiperescaladores em tempo real para total tolerância a desastres físicos."},{"titulo":"Orquestração de Desastres (DRaaS)","descricao":"Planos automatizados de contingência que sobem instâncias na nuvem em minutos, assumindo o processamento caso o datacenter local sofra uma parada total."}]'::jsonb, 'https://infodive.com.br/img/solucoes/protecao-de-dados.jpg', 'Fabricantes homologados', 'Trabalhamos com Veeam, Acronis e IBM.', 3, true, (SELECT id FROM categorias WHERE slug = 'backup-e-recuperacao'), now(), now()),
  (gen_random_uuid(), 'seguranca', 'Cibersegurança Ativa & Zero Trust', 'lock', 'Proteção ponta a ponta contra ameaças virtuais avançadas e conformidade LGPD.', 'Blindagem de perímetro, EDR/MDR proativos e gestão de acessos baseada no princípio do menor privilégio.', 'Nossa metodologia de segurança foca em inteligência de ameaças ativa e monitoramento contínuo. Implementamos políticas rígidas de Zero Trust, garantindo que todo dispositivo e usuário seja autenticado e monitorado ativamente antes de acessar dados críticos da organização.', '[{"titulo":"Zero Trust Network Access (ZTNA)","descricao":"Substituição de VPNs legadas por acessos granulares, contextualizados e seguros para cada colaborador, reduzindo drasticamente a superfície de ataque."},{"titulo":"EDR & MDR Avançados nos Endpoints","descricao":"Agentes inteligentes que detectam e bloqueiam comportamentos suspeitos e ameaças de dia zero em servidores e desktops em tempo real."},{"titulo":"Gestão e Proteção de Dados Sensíveis","descricao":"Descoberta, classificação automática e proteção ativa de dados confidenciais com soluções integradas como IBM Guardium."}]'::jsonb, 'https://infodive.com.br/img/solucoes/seguranca.jpg', 'Fabricantes homologados', 'Trabalhamos com IBM, Acronis e Microsoft.', 4, true, (SELECT id FROM categorias WHERE slug = 'seguranca'), now(), now()),
  (gen_random_uuid(), 'observability', 'Observability & Telemetria Enterprise', 'activity', 'Visão em tempo real da integridade das aplicações, redes e infraestrutura.', 'Métricas consolidadas, logs correlacionados e alertas inteligentes para detectar e mitigar problemas antes que afetem o cliente final.', 'Substituímos o monitoramento passivo por plataformas avançadas de observabilidade. Correlacionamos dados de performance de banco de dados, servidores, rede e experiência de usuário para gerar relatórios preditivos e automatizar a resolução de gargalos de software e hardware.', '[{"titulo":"Monitoramento APM e Infraestrutura","descricao":"Rastreamento completo do ciclo de requisições de software, latência de banco de dados e utilização de recursos físicos da infraestrutura."},{"titulo":"Correlação Inteligente de Logs","descricao":"Centralização e análise de logs com algoritmos avançados para identificar a causa raiz de anomalias em poucos segundos."},{"titulo":"Painéis Executivos & Técnicos","descricao":"Dashboards customizados que traduzem a saúde técnica dos sistemas em métricas e indicadores de negócios diretamente compreensíveis."}]'::jsonb, 'https://infodive.com.br/img/solucoes/observability.jpg', 'Fabricantes homologados', 'Trabalhamos com IBM, Microsoft e AWS.', 5, true, (SELECT id FROM categorias WHERE slug = 'infraestrutura'), now(), now()),
  (gen_random_uuid(), 'virtualizacao', 'Virtualização & Consolidação de Servidores', 'layers', 'Hipervisores robustos para maximizar a eficiência energética e física.', 'Criação de clusters virtuais elásticos de alta densidade e isolamento de cargas com performance nativa.', 'Transformamos datacenters subutilizados em infraestruturas virtuais otimizadas. Gerenciamos e consolidamos ambientes físicos através de hipervisores modernos, maximizando o retorno de investimento (ROI) em computação e facilitando a recuperação em caso de falhas de hardware.', '[{"titulo":"Clusters de Alta Disponibilidade","descricao":"Agrupamento de múltiplos servidores físicos que realocam e iniciam workloads virtuais de forma automática caso algum nó apresente falhas."},{"titulo":"Live Migration Sem Interrupção","descricao":"Migração de sistemas ativos entre servidores físicos em tempo real para manutenções programadas, sem gerar impacto no uso."},{"titulo":"Hiperconvergência Eficiente","descricao":"Fusão lógica de processamento, armazenamento e redes em uma única camada virtualizada simplificada e inteligente."}]'::jsonb, 'https://infodive.com.br/img/solucoes/virtualizacao.jpg', 'Fabricantes homologados', 'Trabalhamos com VMware, Red Hat e Virtuozzo.', 6, true, (SELECT id FROM categorias WHERE slug = 'infraestrutura'), now(), now()),
  (gen_random_uuid(), 'cloud', 'Nuvem Híbrida & Hiperescaladores', 'cloud', 'Arquitetura, migração segura e governança de cloud para alta escalabilidade.', 'Ambientes AWS, Azure ou nuvem privada Infodive integrados de forma transparente sob o conceito de nuvem híbrida.', 'Guiamos sua jornada para a nuvem de ponta a ponta. Seja migrando sistemas complexos para a AWS/Azure, operando nossa nuvem privada dedicada de alta performance ou integrando ambas em um ecossistema híbrido de latência ultra-baixa, estruturamos soluções seguras de acordo com regulamentações corporativas.', '[{"titulo":"Nuvem Híbrida Sob Medida","descricao":"Integração segura entre sua infraestrutura física (on-premises) e nuvens públicas, permitindo processamento elástico sem expor dados confidenciais."},{"titulo":"Governança Híbrida e Compliance","descricao":"Políticas de segurança centralizadas e controle de tráfego que evitam vazamentos e mantêm total conformidade legal."},{"titulo":"Otimização de Custos (FinOps)","descricao":"Monitoramento e redimensionamento constante de recursos em nuvem para eliminar desperdícios e manter as faturas previsíveis."}]'::jsonb, 'https://infodive.com.br/img/solucoes/cloud.jpg', 'Fabricantes homologados', 'Trabalhamos com AWS, Microsoft e Red Hat.', 7, true, (SELECT id FROM categorias WHERE slug = 'cloud'), now(), now()),
  (gen_random_uuid(), 'inteligencia-artificial', 'Infraestrutura para Inteligência Artificial', 'brain', 'Adoção prática, infraestrutura e plataformas especializadas para IA.', 'Desenvolvimento e sustentação de clusters para processamento massivo, modelagem de dados e IA Generativa aplicada.', 'Viabilizamos projetos de Inteligência Artificial desenhando a infraestrutura necessária. Desde o processamento de GPU de alto desempenho e pipelines de dados integrados até a implantação local ou híbrida de modelos de linguagem (LLMs) corporativos com privacidade total.', '[{"titulo":"Infraestrutura de Processamento para IA","descricao":"Configuração e entrega de servidores equipados com GPUs avançadas e arquitetura otimizada para treinamento e inferência de modelos analíticos."},{"titulo":"Plataformas de Modelagem e Dados","descricao":"Pipelines de dados modernos estruturados para alimentar modelos de machine learning de forma automatizada e com total integridade."},{"titulo":"Modelos Privativos (Local LLMs)","descricao":"Instalação de modelos de linguagem inteligência artificial em servidores próprios da empresa para análise de dados com garantia de sigilo industrial."}]'::jsonb, 'https://infodive.com.br/img/solucoes/inteligencia-artificial.jpg', 'Fabricantes homologados', 'Trabalhamos com IBM, Microsoft e AWS.', 8, true, (SELECT id FROM categorias WHERE slug = 'ia'), now(), now()),
  (gen_random_uuid(), 'endpoints', 'Endpoints & Gestão de Dispositivos', 'laptop', 'Gerenciamento centralizado, padronização e segurança de estações de trabalho.', 'Provisionamento automático, controle de patch management e segurança para frotas híbridas de desktops e notebooks.', 'Protegemos e padronizamos a porta de entrada da sua infraestrutura corporativa. Com soluções modernas de Unified Endpoint Management (UEM), mantemos servidores virtuais, notebooks de colaboradores e sistemas remotos constantemente atualizados, auditados e seguros.', '[{"titulo":"Unified Endpoint Management (UEM)","descricao":"Gerenciamento centralizado de sistemas operacionais híbridos (Windows, macOS, Linux) para auditorias de segurança e políticas unificadas."},{"titulo":"Distribuição e Patching Automático","descricao":"Atualizações de segurança críticas implantadas sem interrupção de produtividade dos colaboradores e com relatórios automáticos de conformidade."},{"titulo":"Segurança de Dispositivos Remotos","descricao":"Criptografia de disco local compulsória, bloqueio de portas USB e isolamento de máquinas perdidas ou roubadas para proteção total de informações corporativas."}]'::jsonb, 'https://infodive.com.br/img/solucoes/endpoints.jpg', 'Fabricantes homologados', 'Trabalhamos com Microsoft, Acronis e Apple.', 9, true, (SELECT id FROM categorias WHERE slug = 'seguranca'), now(), now())
ON CONFLICT (slug) DO NOTHING;

UPDATE solucoes
SET
  recurso_chave_1 = COALESCE(NULLIF(recurso_chave_1, ''), features->0->>'titulo'),
  recurso_chave_2 = COALESCE(NULLIF(recurso_chave_2, ''), features->1->>'titulo'),
  recurso_chave_3 = COALESCE(NULLIF(recurso_chave_3, ''), features->2->>'titulo')
WHERE features IS NOT NULL
  AND (
    recurso_chave_1 IS NULL OR recurso_chave_1 = ''
    OR recurso_chave_2 IS NULL OR recurso_chave_2 = ''
    OR recurso_chave_3 IS NULL OR recurso_chave_3 = ''
  );

-- ========== Junção N:N solucoes_fabricantes (vendors de cada solução) ==========
INSERT INTO solucoes_fabricantes (solucao_id, fabricante_id)
SELECT s.id, f.id
FROM solucoes s
JOIN fabricantes f ON
     (s.slug = 'infraestrutura'          AND f.slug IN ('dell', 'lenovo', 'hpe'))
  OR (s.slug = 'armazenamento'           AND f.slug IN ('ibm', 'dell', 'lenovo'))
  OR (s.slug = 'protecao-de-dados'       AND f.slug IN ('veeam', 'acronis', 'ibm'))
  OR (s.slug = 'seguranca'               AND f.slug IN ('ibm', 'acronis', 'microsoft'))
  OR (s.slug = 'observability'           AND f.slug IN ('ibm', 'microsoft', 'aws'))
  OR (s.slug = 'virtualizacao'           AND f.slug IN ('vmware', 'red-hat', 'virtuozzo'))
  OR (s.slug = 'cloud'                   AND f.slug IN ('aws', 'microsoft', 'red-hat'))
  OR (s.slug = 'inteligencia-artificial' AND f.slug IN ('ibm', 'microsoft', 'aws'))
  OR (s.slug = 'endpoints'               AND f.slug IN ('microsoft', 'acronis', 'apple'))
ON CONFLICT DO NOTHING;

-- ========== Administrador de teste para desenvolvimento (allowlist) ==========
INSERT INTO admins_autorizados (id, email, nome, ativo, criado_em)
VALUES (gen_random_uuid(), 'admin@infodive.com.br', 'Admin Teste', true, now())
ON CONFLICT (email) DO NOTHING;

-- ========== Serviços (derivados dos serviços que cada produto integra) ==========
INSERT INTO servicos (id, slug, nome, descricao, icone, ordem, ativo, created_at, updated_at)
VALUES
  (gen_random_uuid(), 'implementacao', 'Implementação', 'Deploy e configuração das soluções no seu ambiente.', 'wrench', 1, true, now(), now()),
  (gen_random_uuid(), 'sustentacao-24-7', 'Sustentação 24/7', 'Suporte e operação contínuos via NOC, 24 horas por dia.', 'headphones', 2, true, now(), now()),
  (gen_random_uuid(), 'conformidade', 'Conformidade', 'Adequação a LGPD, PCI-DSS e demais normas regulatórias.', 'shield-check', 3, true, now(), now()),
  (gen_random_uuid(), 'draas', 'DRaaS', 'Disaster Recovery as a Service com failover orquestrado.', 'life-buoy', 4, true, now(), now()),
  (gen_random_uuid(), 'projeto-deploy', 'Projeto & Deploy', 'Projeto, dimensionamento e implantação de infraestrutura.', 'server-cog', 5, true, now(), now()),
  (gen_random_uuid(), 'monitoramento', 'Monitoramento', 'Observabilidade e telemetria proativa do ambiente.', 'activity', 6, true, now(), now()),
  (gen_random_uuid(), 'arquitetura', 'Arquitetura', 'Desenho de arquitetura e estratégia de TI.', 'cog', 7, true, now(), now()),
  (gen_random_uuid(), 'migracao', 'Migração', 'Migração de cargas e dados com segurança e baixo downtime.', 'refresh-ccw', 8, true, now(), now()),
  (gen_random_uuid(), 'cloud-gerenciada', 'Cloud Gerenciada', 'Operação e governança de ambientes de nuvem.', 'cloud', 9, true, now(), now())
ON CONFLICT (slug) DO NOTHING;

-- ========== Produtos (products-data.ts) — FKs resolvidas por slug ==========
INSERT INTO produtos (id, slug, nome, subcategoria, descricao_curta, descricao_completa, diferenciais, casos_de_uso, servicos_eyebrow, servicos_titulo, servicos_descricao, imagem_url, destaque, ativo, fabricante_id, solucao_id, categoria_id, created_at, updated_at)
VALUES
  (gen_random_uuid(), 'ibm-guardium', 'IBM Guardium', 'Segurança de Dados', 'Descoberta, monitoramento e proteção de dados sensíveis em tempo real.', 'O IBM Guardium oferece visibilidade total sobre onde estão seus dados sensíveis e quem os acessa. Monitora atividades em bancos de dados, data warehouses e ambientes de nuvem, aplicando políticas de conformidade (LGPD, PCI-DSS) e detectando comportamentos anômalos antes que virem incidentes.', '[{"titulo":"Descoberta automática","descricao":"Mapeia dados sensíveis em ambientes on-prem e multicloud sem agentes pesados."},{"titulo":"Análise de risco em tempo real","descricao":"Detecta acessos anômalos e tentativas de exfiltração com analytics comportamental."},{"titulo":"Conformidade contínua","descricao":"Relatórios prontos para LGPD, PCI-DSS, SOX e auditorias recorrentes."}]'::jsonb, '[{"titulo":"Proteção de dados regulados","descricao":"Instituições financeiras e saúde que precisam comprovar conformidade."},{"titulo":"Auditoria de acessos","descricao":"Rastreabilidade completa de quem acessou quais dados e quando."},{"titulo":"Resposta a incidentes","descricao":"Alertas acionáveis integrados ao SOC para conter ameaças rapidamente."}]'::jsonb, 'Integra com nossos serviços', 'Do projeto à operação', 'Implementamos, migramos e sustentamos sua plataforma de ponta a ponta.', 'https://infodive.com.br/img/produtos/ibm-guardium.jpg', true, true, (SELECT id FROM fabricantes WHERE slug = 'ibm'), (SELECT id FROM solucoes WHERE slug = 'seguranca'), (SELECT id FROM categorias WHERE slug = 'seguranca'), now(), now()),
  (gen_random_uuid(), 'veeam-data-platform', 'Veeam Data Platform', 'Backup & Recuperação', 'Backup e recuperação confiáveis para ambientes híbridos e multicloud.', 'A Veeam Data Platform unifica backup, recuperação e proteção contra ransomware em uma única plataforma. Com backups imutáveis, recuperação instantânea e verificação automática de restauração, garante a continuidade do negócio mesmo nos piores cenários.', '[{"titulo":"Backups imutáveis","descricao":"Cópias à prova de ransomware (WORM) que não podem ser alteradas ou apagadas."},{"titulo":"Recuperação instantânea","descricao":"Restaure VMs, bancos e arquivos em minutos, não em horas."},{"titulo":"Multicloud nativo","descricao":"Proteção consistente em VMware, Hyper-V, AWS, Azure e Microsoft 365."}]'::jsonb, '[{"titulo":"Defesa contra ransomware","descricao":"Camada imutável que garante recuperação sem pagar resgate."},{"titulo":"Disaster Recovery","descricao":"Failover orquestrado para um site secundário com RTO baixo."},{"titulo":"Proteção de Microsoft 365","descricao":"Backup de e-mails, Teams e SharePoint fora da retenção nativa."}]'::jsonb, 'Integra com nossos serviços', 'Do projeto à operação', 'Implementamos, migramos e sustentamos sua plataforma de ponta a ponta.', 'https://infodive.com.br/img/produtos/veeam-data-platform.jpg', true, true, (SELECT id FROM fabricantes WHERE slug = 'veeam'), (SELECT id FROM solucoes WHERE slug = 'protecao-de-dados'), (SELECT id FROM categorias WHERE slug = 'backup-e-recuperacao'), now(), now()),
  (gen_random_uuid(), 'dell-poweredge', 'Dell PowerEdge', 'Servidores', 'Servidores de alta performance para as cargas mais críticas do negócio.', 'Os servidores Dell PowerEdge entregam a base de computação para workloads exigentes — de virtualização densa a inteligência artificial. Com gerenciamento iDRAC, segurança em nível de hardware e escalabilidade modular, sustentam operações que não podem parar.', '[{"titulo":"Performance escalável","descricao":"Plataformas de 1 a 4 sockets para crescer conforme a demanda."},{"titulo":"Segurança no silício","descricao":"Root of Trust e boot verificado protegem desde o firmware."},{"titulo":"Gestão simplificada","descricao":"Automação de provisionamento e telemetria via iDRAC e OpenManage."}]'::jsonb, '[{"titulo":"Virtualização densa","descricao":"Consolide dezenas de VMs por host com alta disponibilidade."},{"titulo":"Cargas de IA/ML","descricao":"Configurações com GPU para treinamento e inferência."},{"titulo":"Edge computing","descricao":"Modelos compactos para filiais e ambientes de borda."}]'::jsonb, 'Integra com nossos serviços', 'Do projeto à operação', 'Implementamos, migramos e sustentamos sua plataforma de ponta a ponta.', 'https://infodive.com.br/img/produtos/dell-poweredge.jpg', false, true, (SELECT id FROM fabricantes WHERE slug = 'dell'), (SELECT id FROM solucoes WHERE slug = 'infraestrutura'), (SELECT id FROM categorias WHERE slug = 'infraestrutura'), now(), now()),
  (gen_random_uuid(), 'acronis-cyber-protect', 'Acronis Cyber Protect', 'Backup & Cibersegurança', 'Cibersegurança e backup unificados em uma única solução integrada.', 'O Acronis Cyber Protect combina backup, anti-malware com IA e gestão de proteção numa só plataforma. Reduz a complexidade de operar ferramentas separadas e garante que os dados estejam protegidos e recuperáveis mesmo sob ataque ativo.', '[{"titulo":"Proteção unificada","descricao":"Backup e EDR no mesmo agente, sem conflitos entre ferramentas."},{"titulo":"Anti-ransomware com IA","descricao":"Detecção comportamental que reverte alterações maliciosas."},{"titulo":"Gestão centralizada","descricao":"Console único para políticas, alertas e recuperação."}]'::jsonb, '[{"titulo":"PMEs e filiais","descricao":"Proteção completa sem time de segurança dedicado."},{"titulo":"Endpoints remotos","descricao":"Backup e defesa de notebooks fora da rede corporativa."},{"titulo":"Recuperação confiável","descricao":"Restauração validada após incidentes de segurança."}]'::jsonb, 'Integra com nossos serviços', 'Do projeto à operação', 'Implementamos, migramos e sustentamos sua plataforma de ponta a ponta.', 'https://infodive.com.br/img/produtos/acronis-cyber-protect.jpg', false, true, (SELECT id FROM fabricantes WHERE slug = 'acronis'), (SELECT id FROM solucoes WHERE slug = 'seguranca'), (SELECT id FROM categorias WHERE slug = 'seguranca'), now(), now()),
  (gen_random_uuid(), 'red-hat-openshift', 'Red Hat OpenShift', 'Kubernetes & Containers', 'Plataforma Kubernetes corporativa para nuvem pública, privada e híbrida.', 'O Red Hat OpenShift é a plataforma de containers líder para modernizar aplicações e padronizar a entrega de software. Oferece Kubernetes endurecido, pipelines de CI/CD integrados e operação consistente em qualquer nuvem ou datacenter.', '[{"titulo":"Híbrido de verdade","descricao":"Mesma experiência on-prem, em nuvem pública e na borda."},{"titulo":"Segurança integrada","descricao":"Políticas, RBAC e supply chain seguro por padrão."},{"titulo":"Produtividade dev","descricao":"CI/CD, GitOps e catálogos de serviços prontos para times."}]'::jsonb, '[{"titulo":"Modernização de apps","descricao":"Migre monólitos para microsserviços com containers."},{"titulo":"Plataforma interna","descricao":"Self-service para times de desenvolvimento (IDP)."},{"titulo":"Workloads de IA","descricao":"Orquestração de modelos e pipelines de dados em escala."}]'::jsonb, 'Integra com nossos serviços', 'Do projeto à operação', 'Implementamos, migramos e sustentamos sua plataforma de ponta a ponta.', 'https://infodive.com.br/img/produtos/red-hat-openshift.jpg', true, true, (SELECT id FROM fabricantes WHERE slug = 'red-hat'), (SELECT id FROM solucoes WHERE slug = 'cloud'), (SELECT id FROM categorias WHERE slug = 'cloud'), now(), now()),
  (gen_random_uuid(), 'microsoft-azure', 'Microsoft Azure', 'Nuvem Pública', 'Nuvem escalável para modernização, inovação e analytics em escala global.', 'A nuvem Microsoft Azure oferece um catálogo completo de serviços — computação, dados, IA e segurança — com presença global. A Infodive projeta, migra e gerencia ambientes Azure com governança de custos (FinOps) e segurança Zero Trust.', '[{"titulo":"Escala global","descricao":"Datacenters em dezenas de regiões com baixa latência."},{"titulo":"IA e dados","descricao":"Serviços gerenciados de IA, analytics e bancos de dados."},{"titulo":"Governança de custos","descricao":"FinOps e tags para previsibilidade e otimização contínua."}]'::jsonb, '[{"titulo":"Migração para a nuvem","descricao":"Lift-and-shift ou modernização de cargas legadas."},{"titulo":"Ambientes híbridos","descricao":"Integração com datacenter via Azure Arc e ExpressRoute."},{"titulo":"Plataformas de dados","descricao":"Lakehouse e analytics com Synapse e Fabric."}]'::jsonb, 'Integra com nossos serviços', 'Do projeto à operação', 'Implementamos, migramos e sustentamos sua plataforma de ponta a ponta.', 'https://infodive.com.br/img/produtos/microsoft-azure.jpg', false, true, (SELECT id FROM fabricantes WHERE slug = 'microsoft'), (SELECT id FROM solucoes WHERE slug = 'cloud'), (SELECT id FROM categorias WHERE slug = 'cloud'), now(), now()),
  (gen_random_uuid(), 'ibm-flashsystem', 'IBM FlashSystem', 'Storage All-Flash', 'Armazenamento all-flash de alta performance com proteção contra ransomware.', 'O IBM FlashSystem entrega latência consistente em microssegundos com eficiência de dados por hardware (compressão e deduplicação). Inclui Safeguarded Copies imutáveis e detecção de anomalias por IA, unindo performance e resiliência cibernética no storage.', '[{"titulo":"Latência previsível","descricao":"Resposta em microssegundos mesmo sob carga intensa."},{"titulo":"Eficiência por hardware","descricao":"Compressão e dedup sem impacto na performance."},{"titulo":"Resiliência cibernética","descricao":"Cópias imutáveis e detecção de ransomware no storage."}]'::jsonb, '[{"titulo":"Bancos de dados críticos","descricao":"Workloads transacionais que exigem baixa latência."},{"titulo":"Consolidação de storage","descricao":"Reduza TCO unificando cargas em uma plataforma."},{"titulo":"Proteção de dados primários","descricao":"Recuperação rápida a partir de cópias imutáveis."}]'::jsonb, 'Integra com nossos serviços', 'Do projeto à operação', 'Implementamos, migramos e sustentamos sua plataforma de ponta a ponta.', 'https://infodive.com.br/img/produtos/ibm-flashsystem.jpg', false, true, (SELECT id FROM fabricantes WHERE slug = 'ibm'), (SELECT id FROM solucoes WHERE slug = 'armazenamento'), (SELECT id FROM categorias WHERE slug = 'infraestrutura'), now(), now()),
  (gen_random_uuid(), 'lenovo-thinkagile', 'Lenovo ThinkAgile', 'Hiperconvergência (HCI)', 'Infraestrutura hiperconvergente que simplifica datacenter e filiais.', 'As plataformas Lenovo ThinkAgile integram computação, armazenamento e rede em appliances hiperconvergentes pré-validados. Reduzem a complexidade do datacenter, aceleram a implantação e escalam de forma linear conforme o negócio cresce.', '[{"titulo":"Implantação acelerada","descricao":"Appliances pré-validados prontos para produção em horas."},{"titulo":"Escala linear","descricao":"Adicione nós sem rearquitetar o ambiente."},{"titulo":"Operação simplificada","descricao":"Gestão unificada de compute, storage e rede."}]'::jsonb, '[{"titulo":"Modernização de datacenter","descricao":"Substitua silos por uma stack convergente."},{"titulo":"VDI","descricao":"Desktops virtuais com performance previsível."},{"titulo":"Filiais (ROBO)","descricao":"Infraestrutura compacta e gerenciada remotamente."}]'::jsonb, 'Integra com nossos serviços', 'Do projeto à operação', 'Implementamos, migramos e sustentamos sua plataforma de ponta a ponta.', 'https://infodive.com.br/img/produtos/lenovo-thinkagile.jpg', false, true, (SELECT id FROM fabricantes WHERE slug = 'lenovo'), (SELECT id FROM solucoes WHERE slug = 'virtualizacao'), (SELECT id FROM categorias WHERE slug = 'infraestrutura'), now(), now())
ON CONFLICT (slug) DO NOTHING;

-- ========== Junção N:N produto_servico (serviços que cada produto integra) ==========
INSERT INTO produto_servico (produto_id, servico_id)
SELECT p.id, s.id
FROM produtos p
JOIN servicos s ON
     (p.slug = 'ibm-guardium'          AND s.slug IN ('implementacao', 'sustentacao-24-7', 'conformidade'))
  OR (p.slug = 'veeam-data-platform'   AND s.slug IN ('implementacao', 'draas', 'sustentacao-24-7'))
  OR (p.slug = 'dell-poweredge'        AND s.slug IN ('projeto-deploy', 'sustentacao-24-7', 'monitoramento'))
  OR (p.slug = 'acronis-cyber-protect' AND s.slug IN ('implementacao', 'sustentacao-24-7', 'monitoramento'))
  OR (p.slug = 'red-hat-openshift'     AND s.slug IN ('arquitetura', 'migracao', 'sustentacao-24-7'))
  OR (p.slug = 'microsoft-azure'       AND s.slug IN ('migracao', 'cloud-gerenciada', 'sustentacao-24-7'))
  OR (p.slug = 'ibm-flashsystem'       AND s.slug IN ('projeto-deploy', 'sustentacao-24-7', 'monitoramento'))
  OR (p.slug = 'lenovo-thinkagile'     AND s.slug IN ('projeto-deploy', 'migracao', 'sustentacao-24-7'))
ON CONFLICT DO NOTHING;

-- ========== Conteúdos / Blog (blog-data.ts) — categoria_id e fabricante_id resolvidos por slug ==========
INSERT INTO conteudos (id, titulo, slug, tipo, origem, descricao, conteudo, imagem_url, url_externa, social_post_id, autor, tempo_leitura, publicado_em, ativo, destaque, categoria_id, fabricante_id, produto_id, created_at, updated_at)
VALUES
  (gen_random_uuid(), 'Como o IBM Guardium protege dados sensíveis em ambientes híbridos', 'ibm-guardium-dados-sensiveis-ambientes-hibridos', 'ARTIGO', 'INTERNO', 'Entenda como implementar conformidade LGPD sem impactar a performance do ambiente.', '[{"tipo":"paragrafo","texto":"Proteger dados sensíveis deixou de ser uma preocupação restrita ao time de segurança e passou a ser tema de conselho. Com a LGPD, qualquer vazamento envolvendo dados pessoais expõe a empresa a multas, danos reputacionais e perda de confiança do cliente. O desafio cresce em ambientes híbridos, onde a informação transita entre datacenter, nuvem pública e SaaS."},{"tipo":"subtitulo","texto":"Visibilidade antes de controle"},{"tipo":"paragrafo","texto":"Não se protege o que não se enxerga. O IBM Guardium começa pela descoberta e classificação automática de dados sensíveis espalhados pelos repositórios — bancos relacionais, NoSQL, data lakes e arquivos. A partir desse mapa, é possível definir políticas de acesso e monitoramento com base no risco real de cada ativo."},{"tipo":"subtitulo","texto":"Monitoração contínua sem penalizar a performance"},{"tipo":"paragrafo","texto":"A maior objeção dos DBAs costuma ser o impacto na performance. O Guardium opera com agentes leves (S-TAPs) que interceptam o tráfego de banco fora do caminho crítico da transação, registrando quem acessou o quê, quando e de onde — sem adicionar latência perceptível à aplicação."},{"tipo":"lista","itens":["Auditoria independente do DBA, separando funções e evitando conflito de interesse.","Alertas em tempo real para acessos anômalos ou exfiltração de dados.","Mascaramento dinâmico para ambientes de homologação e desenvolvimento.","Relatórios prontos para auditorias de LGPD, PCI-DSS e ISO 27001."]},{"tipo":"citacao","texto":"Conformidade não é um projeto com data de término — é um processo contínuo de visibilidade, controle e evidência."},{"tipo":"subtitulo","texto":"Como a Infodive conduz o projeto"},{"tipo":"paragrafo","texto":"Implantamos o Guardium em fases: começamos por um assessment dos repositórios críticos, definimos as políticas junto ao time de dados e ativamos a monitoração em modo observação antes de aplicar bloqueios. Esse método reduz falsos positivos e garante adoção sem fricção com as áreas de negócio."}]'::jsonb, NULL, NULL, NULL, 'Equipe Infodive', '7 min de leitura', '2026-05-18 10:00:00', true, true, (SELECT id FROM solucoes WHERE slug = 'seguranca'), (SELECT id FROM fabricantes WHERE slug = 'ibm'), NULL, now(), now()),
  (gen_random_uuid(), 'Guia completo de recuperação de desastres com Veeam Data Platform', 'recuperacao-de-desastres-veeam-data-platform', 'WHITEPAPER', 'INTERNO', 'Estratégias práticas para atingir RTO abaixo de 4 horas em ambientes críticos.', '[{"tipo":"paragrafo","texto":"Um plano de recuperação de desastres só vale o que entrega quando testado sob pressão. Ter backup não é o mesmo que ter capacidade de recuperação. Este guia apresenta a abordagem que usamos para desenhar estratégias de DR com objetivos de RTO e RPO realistas e mensuráveis."},{"tipo":"subtitulo","texto":"RTO e RPO: traduzindo risco em números"},{"tipo":"paragrafo","texto":"Antes de escolher tecnologia, é preciso classificar as aplicações por criticidade de negócio. Sistemas que sustentam faturamento exigem RTO de minutos; um portal interno tolera horas. Esse mapeamento define onde investir em replicação contínua e onde o backup tradicional já é suficiente."},{"tipo":"subtitulo","texto":"Backup imutável contra ransomware"},{"tipo":"paragrafo","texto":"Ransomware moderno busca apagar ou criptografar os backups antes de atacar a produção. Com repositórios imutáveis (hardened repository e object lock), o Veeam garante cópias que não podem ser alteradas nem excluídas durante o período definido — sua última linha de defesa."},{"tipo":"lista","itens":["Regra 3-2-1-1-0: três cópias, dois meios, uma off-site, uma imutável, zero erros nos testes.","Replicação para site secundário ou nuvem com failover orquestrado.","Instant Recovery para subir VMs direto do backup em minutos.","SureBackup: testes automáticos de restauração validando o plano de DR."]},{"tipo":"citacao","texto":"Um backup que nunca foi testado é apenas uma esperança. DR de verdade se prova com ensaios periódicos."},{"tipo":"subtitulo","texto":"Atingindo RTO abaixo de 4 horas"},{"tipo":"paragrafo","texto":"Combinando Instant Recovery, replicação e runbooks de failover documentados, ambientes críticos atingem RTO inferior a quatro horas de forma consistente. A Infodive entrega o plano, automatiza os testes e acompanha os ensaios trimestrais junto ao cliente."}]'::jsonb, NULL, NULL, NULL, 'Equipe Infodive', '9 min de leitura', '2026-05-10 10:00:00', true, true, (SELECT id FROM solucoes WHERE slug = 'protecao-de-dados'), (SELECT id FROM fabricantes WHERE slug = 'veeam'), NULL, now(), now()),
  (gen_random_uuid(), 'Como reduzimos 40% dos custos de cloud de uma fintech em 3 meses', 'reducao-de-custos-cloud-fintech', 'CASE', 'INTERNO', 'Da auditoria ao FinOps: o processo que a Infodive usou para recuperar controle do budget.', '[{"tipo":"paragrafo","texto":"Uma fintech em crescimento acelerado nos procurou com um problema comum: a conta de cloud crescia mais rápido que a receita, sem que ninguém soubesse exatamente o porquê. Em 90 dias, reduzimos 40% do custo mensal sem comprometer performance nem disponibilidade."},{"tipo":"subtitulo","texto":"O diagnóstico: para onde o dinheiro estava indo"},{"tipo":"paragrafo","texto":"A primeira etapa foi tornar o gasto visível. Mapeamos recursos por aplicação, ambiente e time, e descobrimos os suspeitos de sempre: máquinas superdimensionadas, ambientes de teste ligados 24/7, discos órfãos e ausência total de reservas de capacidade."},{"tipo":"lista","itens":["Rightsizing de VMs com base em telemetria real de CPU e memória.","Desligamento automático de ambientes de não-produção fora do horário comercial.","Reserved Instances e Savings Plans para workloads previsíveis.","Limpeza de discos, snapshots e IPs órfãos sem uso."]},{"tipo":"subtitulo","texto":"De economia pontual a cultura de FinOps"},{"tipo":"paragrafo","texto":"Cortar custo uma vez é fácil; manter o controle é o desafio. Implantamos um ciclo de FinOps com dashboards de custo por time, alertas de anomalia e revisões mensais. A engenharia passou a enxergar o impacto financeiro de cada decisão de arquitetura."},{"tipo":"citacao","texto":"Cloud sem governança é dinheiro jogado fora. FinOps transforma custo em uma métrica de engenharia, não só de finanças."},{"tipo":"paragrafo","texto":"Três meses depois, além dos 40% de redução, a fintech ganhou previsibilidade de budget e passou a tratar eficiência de nuvem como parte do processo de desenvolvimento."}]'::jsonb, NULL, NULL, NULL, 'Equipe Infodive', '6 min de leitura', '2026-05-02 10:00:00', true, true, (SELECT id FROM solucoes WHERE slug = 'cloud'), (SELECT id FROM fabricantes WHERE slug = 'microsoft'), NULL, now(), now()),
  (gen_random_uuid(), 'VMware vs Proxmox: qual escolher para modernizar seu datacenter?', 'vmware-vs-proxmox-modernizar-datacenter', 'ARTIGO', 'INTERNO', 'Análise técnica e comercial das duas plataformas mais usadas em virtualização enterprise.', '[{"tipo":"paragrafo","texto":"As mudanças de licenciamento dos últimos anos reacenderam uma pergunta nas reuniões de TI: continuar no VMware ou migrar para Proxmox? Não existe resposta universal — existe a resposta certa para o seu contexto. Vamos comparar as duas plataformas com honestidade técnica e comercial."},{"tipo":"subtitulo","texto":"Maturidade e ecossistema"},{"tipo":"paragrafo","texto":"O VMware oferece um ecossistema maduro, suporte enterprise robusto e integração nativa com praticamente todo fabricante de storage e backup. É a escolha segura para ambientes de missão crítica com requisitos rígidos de SLA e compliance."},{"tipo":"subtitulo","texto":"Custo e flexibilidade"},{"tipo":"paragrafo","texto":"O Proxmox, open source e baseado em KVM e LXC, elimina o custo de licença e entrega excelente performance. Em troca, exige mais maturidade da equipe interna e um parceiro técnico sólido para arquitetura, alta disponibilidade e suporte."},{"tipo":"lista","itens":["Workloads críticos com forte exigência de SLA tendem a permanecer no VMware.","Ambientes de desenvolvimento, laboratório e cargas elásticas se beneficiam do Proxmox.","Cenários híbridos — VMware na produção, Proxmox no resto — são cada vez mais comuns.","O custo total deve considerar licença, suporte, capacitação e risco operacional."]},{"tipo":"citacao","texto":"A pergunta certa não é ''qual é melhor?'', mas ''qual entrega o melhor resultado para a minha operação e a minha equipe?''."},{"tipo":"paragrafo","texto":"A Infodive conduz provas de conceito com os dois hypervisors e apresenta uma análise de TCO de três anos, para que a decisão seja baseada em dados — não em modismo."}]'::jsonb, NULL, NULL, NULL, 'Equipe Infodive', '8 min de leitura', '2026-04-28 10:00:00', true, false, (SELECT id FROM solucoes WHERE slug = 'virtualizacao'), (SELECT id FROM fabricantes WHERE slug = 'vmware'), NULL, now(), now()),
  (gen_random_uuid(), 'Datasheet: Servidores ThinkSystem SR650 V3', 'datasheet-lenovo-thinksystem-sr650-v3', 'DATASHEET', 'INTERNO', 'Especificações técnicas, configurações disponíveis e casos de uso recomendados.', '[{"tipo":"paragrafo","texto":"O Lenovo ThinkSystem SR650 V3 é um servidor rack 2U de duplo socket projetado para o coração do datacenter corporativo: virtualização, bancos de dados, cargas de IA e ambientes de uso geral que exigem desempenho e densidade."},{"tipo":"subtitulo","texto":"Especificações principais"},{"tipo":"lista","itens":["Processadores Intel Xeon Scalable de 5ª geração, até 64 núcleos por socket.","Até 8 TB de memória DDR5 em 32 slots, com suporte a ECC.","Até 20 baias NVMe/SAS/SATA para flexibilidade de armazenamento.","Slots PCIe Gen5 para aceleradores GPU e adaptadores de alta velocidade.","Fontes redundantes Titanium e refrigeração otimizada para eficiência energética."]},{"tipo":"subtitulo","texto":"Casos de uso recomendados"},{"tipo":"paragrafo","texto":"O SR650 V3 é a base ideal para clusters de virtualização VMware ou Proxmox, infraestrutura hiperconvergente, bancos de dados transacionais e inferência de IA. Sua densidade de memória e expansão NVMe atendem desde consolidação até workloads de alta performance."},{"tipo":"citacao","texto":"Dimensionar corretamente o servidor na origem evita gargalos caros — e retrabalho — no futuro."},{"tipo":"paragrafo","texto":"A Infodive ajuda a configurar o SR650 V3 sob medida para o seu workload, com homologação de fábrica e suporte local. Solicite a configuração ideal para o seu projeto."}]'::jsonb, NULL, NULL, NULL, 'Equipe Infodive', '4 min de leitura', '2026-04-22 10:00:00', true, false, (SELECT id FROM solucoes WHERE slug = 'infraestrutura'), (SELECT id FROM fabricantes WHERE slug = 'lenovo'), NULL, now(), now()),
  (gen_random_uuid(), 'Proteção contra ransomware em rede hospitalar com Acronis Cyber Protect', 'ransomware-rede-hospitalar-acronis-cyber-protect', 'CASE', 'INTERNO', 'Como implementamos backup imutável e detecção de comportamento em 72 horas.', '[{"tipo":"paragrafo","texto":"Em ambientes de saúde, indisponibilidade não é só prejuízo financeiro — é risco à vida. Uma rede hospitalar nos acionou após um incidente de ransomware no setor, buscando blindar sua operação rapidamente. Em 72 horas, colocamos em pé uma camada de proteção e recuperação confiável."},{"tipo":"subtitulo","texto":"O contexto: alto risco, baixa tolerância a downtime"},{"tipo":"paragrafo","texto":"Sistemas de prontuário eletrônico, PACS de imagens e integrações com laboratório precisam estar disponíveis 24/7. Qualquer parada afeta atendimento. Era preciso uma solução que unisse backup, antimalware e detecção comportamental sem multiplicar consoles."},{"tipo":"subtitulo","texto":"A implementação em 72 horas"},{"tipo":"lista","itens":["Backup imutável local e em nuvem, protegido contra exclusão.","Detecção comportamental de ransomware com reversão automática de arquivos.","Política de proteção unificada para servidores, endpoints e cargas virtualizadas.","Testes de restauração validando o RTO dos sistemas críticos."]},{"tipo":"citacao","texto":"Ransomware não avisa antes de atacar. Quando ele chega, o que importa é a velocidade e a confiabilidade da recuperação."},{"tipo":"paragrafo","texto":"Com o Acronis Cyber Protect, a rede hospitalar passou a contar com proteção integrada e recuperação testada. O time de TI ganhou visibilidade central e a direção, tranquilidade para focar no que importa: o paciente."}]'::jsonb, NULL, NULL, NULL, 'Equipe Infodive', '6 min de leitura', '2026-04-15 10:00:00', true, false, (SELECT id FROM solucoes WHERE slug = 'seguranca'), (SELECT id FROM fabricantes WHERE slug = 'acronis'), NULL, now(), now()),
  (gen_random_uuid(), 'FinOps na prática: controlando custos de cloud com Instana e Turbonomic', 'finops-na-pratica-instana-turbonomic', 'WHITEPAPER', 'INTERNO', 'Framework e ferramentas para implementar governança financeira em ambientes multi-cloud.', '[{"tipo":"paragrafo","texto":"FinOps não é uma ferramenta — é uma disciplina que une engenharia, finanças e negócio em torno do valor entregue por cada real gasto em nuvem. Mas a disciplina precisa de instrumentação. É aí que entram observabilidade e automação de recursos."},{"tipo":"subtitulo","texto":"Observabilidade como base da decisão"},{"tipo":"paragrafo","texto":"O IBM Instana entrega visibilidade de ponta a ponta da performance das aplicações, correlacionando consumo de recursos com experiência do usuário. Sem essa visão, qualquer corte de custo é um chute que pode degradar o serviço."},{"tipo":"subtitulo","texto":"Automação de recursos com Turbonomic"},{"tipo":"paragrafo","texto":"O Turbonomic vai além de recomendar: ele equilibra continuamente alocação de CPU, memória e storage para garantir performance ao menor custo possível, aplicando ações de forma automatizada e segura conforme as políticas definidas."},{"tipo":"lista","itens":["Inform: tornar o custo visível e atribuível por time e aplicação.","Optimize: rightsizing contínuo e eliminação de desperdício.","Operate: governança recorrente com metas e accountability."]},{"tipo":"citacao","texto":"Governança financeira de nuvem não nasce de planilha — nasce de dados em tempo real e automação confiável."},{"tipo":"paragrafo","texto":"A Infodive implementa o framework FinOps combinando Instana e Turbonomic, estabelecendo o ciclo de inform, optimize e operate adaptado à realidade multi-cloud de cada cliente."}]'::jsonb, NULL, NULL, NULL, 'Equipe Infodive', '8 min de leitura', '2026-04-08 10:00:00', true, false, (SELECT id FROM solucoes WHERE slug = 'observability'), (SELECT id FROM fabricantes WHERE slug = 'ibm'), NULL, now(), now()),
  (gen_random_uuid(), 'IA generativa no ambiente corporativo: por onde começar?', 'ia-generativa-corporativo-por-onde-comecar', 'ARTIGO', 'INTERNO', 'Um guia prático para gestores de TI avaliando a adoção de IA nas operações da empresa.', '[{"tipo":"paragrafo","texto":"A pergunta deixou de ser ''se'' e passou a ser ''como'' adotar IA generativa na empresa. O risco não está em começar tarde, mas em começar sem método — investindo em pilotos vistosos que nunca chegam à produção e não geram valor mensurável."},{"tipo":"subtitulo","texto":"Comece pelo problema, não pela tecnologia"},{"tipo":"paragrafo","texto":"Os melhores casos de uso resolvem dores concretas: atendimento que consome tempo, conhecimento disperso em documentos, processos manuais repetitivos. Escolher um problema bem delimitado e com retorno claro é o que separa um piloto de um produto."},{"tipo":"subtitulo","texto":"Governança e dados desde o primeiro dia"},{"tipo":"paragrafo","texto":"Adotar IA corporativa exige cuidado com privacidade, propriedade dos dados e rastreabilidade das respostas. Plataformas como o watsonx permitem manter o controle sobre onde os dados vivem e como os modelos são governados — requisito inegociável para setores regulados."},{"tipo":"lista","itens":["Defina um caso de uso com ROI mensurável antes de escolher o modelo.","Garanta qualidade e governança dos dados que alimentam a solução.","Mantenha humano no loop nas decisões sensíveis.","Planeje a passagem de piloto para produção desde o início."]},{"tipo":"citacao","texto":"IA generativa no ambiente corporativo não é o futuro — é o presente. O diferencial está na execução disciplinada."},{"tipo":"paragrafo","texto":"A Infodive ajuda a priorizar casos de uso, desenhar a arquitetura e estabelecer a governança necessária para tirar a IA do laboratório e colocá-la para trabalhar."}]'::jsonb, NULL, NULL, NULL, 'Equipe Infodive', '7 min de leitura', '2026-04-01 10:00:00', true, false, (SELECT id FROM solucoes WHERE slug = 'inteligencia-artificial'), (SELECT id FROM fabricantes WHERE slug = 'ibm'), NULL, now(), now()),
  (gen_random_uuid(), 'Demo: PowerEdge R760 em workloads de alta disponibilidade', 'demo-dell-poweredge-r760-alta-disponibilidade', 'VIDEO', 'INTERNO', 'Vídeo técnico mostrando configuração e performance em ambiente de produção simulado.', '[{"tipo":"paragrafo","texto":"Neste vídeo técnico, a equipe Infodive coloca o Dell PowerEdge R760 à prova em um cenário de alta disponibilidade, demonstrando configuração, tolerância a falhas e comportamento sob carga em um ambiente de produção simulado."},{"tipo":"subtitulo","texto":"O que você vai ver na demonstração"},{"tipo":"lista","itens":["Configuração de cluster com failover automático.","Comportamento sob carga com simulação de pico de tráfego.","Testes de tolerância a falhas de fonte, disco e rede.","Telemetria e gerenciamento remoto via iDRAC."]},{"tipo":"subtitulo","texto":"Por que o R760 para alta disponibilidade"},{"tipo":"paragrafo","texto":"Com processadores Intel Xeon Scalable, memória DDR5 e ampla expansão NVMe, o PowerEdge R760 entrega a redundância e a performance necessárias para sustentar aplicações críticas com SLA exigente."},{"tipo":"citacao","texto":"Alta disponibilidade não se improvisa: ela é arquitetada, configurada e testada antes de entrar em produção."},{"tipo":"paragrafo","texto":"Quer ver o R760 rodando no seu cenário? A Infodive realiza demonstrações e provas de conceito sob medida. Fale com nosso time para agendar."}]'::jsonb, NULL, NULL, NULL, 'Equipe Infodive', '12 min de vídeo', '2026-03-25 10:00:00', true, false, (SELECT id FROM solucoes WHERE slug = 'infraestrutura'), (SELECT id FROM fabricantes WHERE slug = 'dell'), NULL, now(), now())
ON CONFLICT (slug) DO NOTHING;

-- ========== Cases (home — carrossel de depoimentos) ==========
INSERT INTO cases (id, segmento, cliente, titulo, desafio, resultado, metrica, autor, cargo, depoimento, imagem_url, ordem, ativo, created_at, updated_at)
SELECT gen_random_uuid(), v.segmento, v.cliente, v.titulo, v.desafio, v.resultado, v.metrica, v.autor, v.cargo, v.depoimento, v.imagem_url, v.ordem, true, now(), now()
FROM (VALUES
  ('Setor Financeiro', 'Banco Regional', 'Alta disponibilidade para o core bancário', 'Quedas frequentes e gargalos de latência em bancos de dados legados no ambiente crítico.', 'Migração para arquitetura multicloud redundante com telemetria centralizada e failover automático.', '99.98% Uptime', 'Carlos Mendes', 'CTO', 'A Infodive transformou nossa operação crítica e nos deu previsibilidade.', 'https://infodive.com.br/img/cases/banco-regional.jpg', 1),
  ('Varejo e E-commerce', 'Rede Cosmos', 'Proteção de dados e endpoints em escala', 'Falta de visibilidade de ameaças e risco de ransomware nas frentes de caixa.', 'Backup imutável em nuvem com restauração instantânea e 142 endpoints monitorados em tempo integral.', '< 10 min RTO', 'Ana Lima', 'Gerente de TI', 'Visibilidade total e recuperação testada nos pontos de venda.', 'https://infodive.com.br/img/cases/rede-cosmos.jpg', 2),
  ('Indústria Pesada', 'Vesta Manufatura', 'Renovação do parque de processamento', 'Cluster de processamento local defasado gerando gargalos operacionais.', 'Consolidação de 12 servidores antigos em 3 nós de alta densidade com replicação ativa.', '+40% Performance', 'Roberto Khalil', 'Diretor de Operações', 'Ganhamos performance e simplificamos drasticamente o gerenciamento.', 'https://infodive.com.br/img/cases/vesta-manufatura.jpg', 3)
) AS v(segmento, cliente, titulo, desafio, resultado, metrica, autor, cargo, depoimento, imagem_url, ordem)
WHERE NOT EXISTS (SELECT 1 FROM cases);

-- ========== Configuração de páginas ==========
INSERT INTO paginas_hero (id, pagina, eyebrow, headline, subtitulo, tagline, updated_at)
VALUES
  (gen_random_uuid(), 'home', 'Infodive IT', 'Tecnologia que integra o seu negócio', 'Soluções de TI corporativa desde 2003.', 'DESDE 2003 INTEGRANDO TECNOLOGIA', now()),
  (gen_random_uuid(), 'produtos', 'Catálogo', 'Produtos homologados', 'As melhores soluções dos líderes de mercado.', NULL, now()),
  (gen_random_uuid(), 'solucoes', 'Soluções', 'O que resolvemos', 'Da infraestrutura à inteligência artificial.', NULL, now()),
  (gen_random_uuid(), 'servicos', 'Serviços', 'Tecnologia é só o começo. Resultado vem da execução.', 'A Infodive não entrega apenas a tecnologia — planejamos, implantamos, migramos e sustentamos o ambiente que mantém sua empresa no ar.', 'execução', now()),
  (gen_random_uuid(), 'sobre', 'Quem Somos', 'Integradores de tecnologia desde 2003.', 'Há mais de duas décadas, a Infodive desenha, implementa e sustenta a infraestrutura crítica de empresas que não podem parar — da arquitetura à operação.', '2003', now()),
  (gen_random_uuid(), 'blog', 'Conteúdos', 'Conhecimento técnico para decisões melhores.', 'Artigos, materiais técnicos e o que a Infodive compartilha nas redes.', 'melhores', now())
ON CONFLICT (pagina) DO NOTHING;

INSERT INTO ctas (id, pagina, titulo, subtitulo, cta_texto, tipo_acao, updated_at)
VALUES
  (gen_random_uuid(), 'solucoes', 'Sua infraestrutura crítica precisa de sustentação?', 'Fale com nossos arquitetos de soluções. Projetamos, implementamos e sustentamos seu ambiente 24/7 com garantia de SLA.', 'Falar com especialista', 'DRAWER', now()),
  (gen_random_uuid(), 'produtos', 'Não achou o que procurava?', 'Nosso catálogo vai muito além desta vitrine. Fale com um especialista e encontramos o produto certo — com o melhor fabricante — para o seu desafio.', 'Falar com especialista', 'DRAWER', now()),
  (gen_random_uuid(), 'servicos', 'Pronto para tirar seu projeto do papel?', 'Do diagnóstico à operação assistida, a Infodive assume o ciclo completo. Conte o desafio — a gente desenha o caminho.', 'Falar com especialista', 'DRAWER', now()),
  (gen_random_uuid(), 'sobre', 'Pronto para escrever o próximo capítulo com a gente?', 'Fale com quem integra tecnologia desde 2003 — e descubra o que um parceiro de verdade muda na sua operação.', 'Falar com a gente', 'DRAWER', now()),
  (gen_random_uuid(), 'blog', 'Quer receber conteúdos técnicos em primeira mão?', 'Artigos, materiais técnicos e o que a Infodive compartilha nas redes. Fale com a gente e acompanhe o que produzimos sobre infraestrutura, segurança e cloud.', 'Falar com um especialista', 'DRAWER', now())
ON CONFLICT (pagina) DO NOTHING;

DELETE FROM secoes_home WHERE secao = 'problemas';

INSERT INTO secoes_home (id, secao, eyebrow, headline, headline_destaque, subtitulo, box_titulo, box_descricao, updated_at)
VALUES
  (gen_random_uuid(), 'solucoes', 'Soluções', 'Um portfólio completo para a sua operação crítica', 'portfólio completo', 'Áreas de atuação.', NULL, NULL, now()),
  (gen_random_uuid(), 'produtos', 'Produtos', 'Em destaque', NULL, 'Selecionados para você.', NULL, NULL, now()),
  (gen_random_uuid(), 'cases', 'Cases', 'Resultados reais', NULL, 'Histórias de clientes.', NULL, NULL, now()),
  (gen_random_uuid(), 'problemas', 'Problemas que resolvemos', 'Desafios complexos de TI. Soluções simples e definitivas.', 'Soluções simples e definitivas.', 'A tecnologia deve impulsionar o seu negócio, não paralisá-lo. Mapeamos os principais gargalos operacionais do mercado e desenvolvemos arquiteturas sob medida para superá-los.', 'Suporte Proativo 24/7/365', 'Sua infraestrutura crítica é monitorada ativamente para conter anomalias antes que virem incidentes.', now())
ON CONFLICT (secao) DO NOTHING;

INSERT INTO hero_home_carousel (id, imagem_url, ordem, ativo, created_at)
SELECT gen_random_uuid(), v.imagem_url, v.ordem, true, now()
FROM (VALUES
  ('https://infodive.com.br/img/hero/1.jpg', 1),
  ('https://infodive.com.br/img/hero/2.jpg', 2)
) AS v(imagem_url, ordem)
WHERE NOT EXISTS (SELECT 1 FROM hero_home_carousel);

INSERT INTO config_footer (id, descricao_empresa, badge_noc, badge_cloud, nome_legal, url_linkedin, url_instagram, url_facebook, updated_at)
SELECT gen_random_uuid(), 'Integradora de tecnologia B2B desde 2003.', 'NOC 24/7', 'Cloud Partner', 'Infodive IT Ltda.', 'https://linkedin.com/company/infodive', 'https://instagram.com/infodive', 'https://facebook.com/infodive', now()
WHERE NOT EXISTS (SELECT 1 FROM config_footer);

INSERT INTO config_blog (id, artigos_eyebrow, artigos_headline, social_eyebrow, social_headline, social_descricao, url_instagram, url_linkedin, updated_at)
SELECT gen_random_uuid(), 'Blog', 'Artigos e novidades', 'Social', 'Acompanhe nas redes', 'Conteúdo diário sobre tecnologia.', 'https://instagram.com/infodive', 'https://linkedin.com/company/infodive', now()
WHERE NOT EXISTS (SELECT 1 FROM config_blog);

INSERT INTO contato_info (id, eyebrow, headline, headline_destaque, subtitulo, email, telefone, endereco, horario_comercial, horario_noc, card_titulo, card_descricao, card_bullets, card_cta_texto, card_status, updated_at)
SELECT gen_random_uuid(), 'Contato', 'Pronto para evoluir a TI da sua empresa?', 'TI da sua empresa', 'Conecte-se com nossos consultores seniores. Estamos prontos para projetar e implementar soluções de infraestrutura e nuvem sob medida para o seu negócio.', 'contato@infodive.com.br', '+55 (51) 3330-0444', 'Av. Cristóvão Colombo, 3000 - Sala 704 | Floresta, Porto Alegre - RS', 'Seg a Sex, 9h às 18h', 'Suporte Crítico NOC: 24/7', 'Precisa de ajuda imediata?', 'Fale com nossos engenheiros e receba uma análise rápida dos requisitos de TI, segurança e nuvem do seu negócio.', '["Resposta em até 1 hora","Diagnóstico inicial sem custo","Especialistas certificados"]'::jsonb, 'Falar com Especialista', 'Especialistas online no momento', now()
WHERE NOT EXISTS (SELECT 1 FROM contato_info);

-- ========== Seções da home ==========
INSERT INTO home_solucoes_bento (id, nome, descricao, icone, imagem_ia_url, ordem, updated_at)
SELECT gen_random_uuid(), v.nome, v.descricao, v.icone, v.imagem_ia_url, v.ordem, now()
FROM (VALUES
  ('Segurança', 'Proteção de ponta a ponta', 'lock', NULL, 1),
  ('Inteligência Artificial', 'IA aplicada ao negócio', 'brain', 'https://infodive.com.br/img/bento/ia.jpg', 2)
) AS v(nome, descricao, icone, imagem_ia_url, ordem)
WHERE NOT EXISTS (SELECT 1 FROM home_solucoes_bento);

INSERT INTO home_seguranca_marquee (id, icone, titulo, corpo, ordem, ativo)
SELECT gen_random_uuid(), v.icone, v.titulo, v.corpo, v.ordem, true
FROM (VALUES
  ('shield', 'Ameaça bloqueada', 'Ransomware contido antes da execução.', 1),
  ('lock', 'Acesso negado', 'Tentativa de invasão barrada pelo firewall.', 2)
) AS v(icone, titulo, corpo, ordem)
WHERE NOT EXISTS (SELECT 1 FROM home_seguranca_marquee);

INSERT INTO home_problemas (id, titulo, descricao, solucao_indicada, href, ordem, ativo)
SELECT gen_random_uuid(), v.titulo, v.descricao, v.solucao_indicada, v.href, v.ordem, true
FROM (VALUES
  ('Instabilidade e quedas constantes nos sistemas', 'Sistemas indisponíveis durante picos de demanda ou operações sazonais geram prejuízos diretos, desgaste com clientes e arranham a reputação da sua marca.', 'Alta Disponibilidade & Cloud Elástica', '/solucoes', 1),
  ('Backups lentos e vulnerabilidade a ataques cibernéticos', 'Políticas manuais de cópias de dados falham quando mais se precisa. Sua empresa está realmente protegida contra ameaças modernas como ransomware?', 'Backup Imutável & Cibersegurança Ativa', '/solucoes', 2),
  ('Servidores obsoletos gargalando a operação', 'Hardware antigo e sistemas legados limitam a velocidade do seu ERP, gerando atrasos crônicos no faturamento, na entrega e na linha de produção.', 'Modernização de Hardware & Servidores Dedicados', '/solucoes', 3),
  ('Dificuldade na integração e adoção prática de IA', 'Embora a IA seja vital para a competitividade, a falta de expertise técnica e infraestrutura especializada impede que projetos de inteligência saiam do papel.', 'IA Aplicada a Negócios & Modelagem de Dados', '/solucoes', 4),
  ('Complexidade e custos inflados com nuvem híbrida', 'Manter dados confidenciais localmente enquanto se aproveita a flexibilidade da nuvem gera desafios de compliance, latência e custos de nuvem imprevisíveis.', 'Gestão Híbrida & Otimização FinOps', '/solucoes', 5)
) AS v(titulo, descricao, solucao_indicada, href, ordem)
WHERE NOT EXISTS (SELECT 1 FROM home_problemas);

INSERT INTO home_trust_stats (id, eyebrow, prefixo, valor, valor_inicial, sufixo, titulo, descricao, ordem)
SELECT gen_random_uuid(), v.eyebrow, v.prefixo, v.valor, v.valor_inicial, v.sufixo, v.titulo, v.descricao, v.ordem
FROM (VALUES
  ('Tradição', 'Desde', 2003, 1990, '', 'História no mercado de TI', 'Consolidando infraestruturas críticas e integrando inovações tecnológicas há mais de duas décadas.', 1),
  ('Confiança', '+', 100, 0, '', 'Clientes ativos e satisfeitos', 'Parcerias sólidas com bancos, hospitais, indústrias e grandes redes varejistas em todo o país.', 2),
  ('Sucesso', '', 100, 0, '%', 'Projetos entregues com sucesso', 'Projetos de alta complexidade em nuvem, migração e segurança executados com taxa perfeita de sucesso.', 3)
) AS v(eyebrow, prefixo, valor, valor_inicial, sufixo, titulo, descricao, ordem)
WHERE NOT EXISTS (SELECT 1 FROM home_trust_stats);

-- Garante que o 3º trust stat (Confiança) exista mesmo se os outros 2 já foram inseridos
INSERT INTO home_trust_stats (id, eyebrow, prefixo, valor, valor_inicial, sufixo, titulo, descricao, ordem)
SELECT gen_random_uuid(), 'Confiança', '+', 100, 0, '', 'Clientes ativos e satisfeitos', 'Parcerias sólidas com bancos, hospitais, indústrias e grandes redes varejistas em todo o país.', 2
WHERE NOT EXISTS (SELECT 1 FROM home_trust_stats WHERE eyebrow = 'Confiança');

-- Corrige a ordem do stat de Disponibilidade/Sucesso para ficar em 3º lugar com valor correto
UPDATE home_trust_stats SET eyebrow = 'Sucesso', prefixo = '', valor = 100, sufixo = '%', titulo = 'Projetos entregues com sucesso', descricao = 'Projetos de alta complexidade em nuvem, migração e segurança executados com taxa perfeita de sucesso.', ordem = 3
WHERE eyebrow IN ('Disponibilidade', 'Sucesso') AND sufixo = '%';


INSERT INTO faq (id, pergunta, resposta, ordem, ativo)
SELECT gen_random_uuid(), v.pergunta, v.resposta, v.ordem, true
FROM (VALUES
  ('Que tipos de suporte a Infodive oferece?', 'Oferecemos suporte completo com atendimento NOC 24/7/365 para incidentes críticos, além de suporte comercial e consultivo estruturado em níveis de atendimento (N1, N2 e N3) com acordos de SLA rígidos para garantir a continuidade da sua operação.', 1),
  ('A Infodive atua com migração e sustentação em nuvem (Cloud)?', 'Sim. Auxiliamos empresas no planejamento estratégico, migração segura (seja por decolagem direta ou refatoração de código) e sustentação contínua de infraestruturas em nuvem pública (AWS e Azure), privada e ambientes híbridos.', 2),
  ('Quais são os prazos de resposta (SLA) para chamados críticos?', 'Para incidentes de gravidade crítica (Nível 1), nosso SLA padrão de resposta inicial é de até 15 minutos, monitorado e gerido de ponta a ponta pelo nosso time de NOC especializado.', 3),
  ('Como funciona a parceria com fabricantes como IBM, Dell, Lenovo e Microsoft?', 'Somos parceiros homologados e certificados das principais marcas de tecnologia globais. Isso nos permite desenhar projetos unificados com hardware oficial, licenciamento correto, suporte de fábrica direto e condições comerciais altamente competitivas.', 4),
  ('Os projetos e serviços da Infodive estão em conformidade com a LGPD?', 'Sim, todos os nossos serviços gerenciados, políticas de backup e projetos de segurança de dados seguem estritamente as diretrizes da LGPD (Lei Geral de Proteção de Dados), garantindo total privacidade e conformidade jurídica para o seu negócio.', 5)
) AS v(pergunta, resposta, ordem)
WHERE NOT EXISTS (SELECT 1 FROM faq);

-- ========== Serviços e quem somos ==========
INSERT INTO servicos_etapas (id, eyebrow, headline, subtitulo, etapas, updated_at)
SELECT gen_random_uuid(), 'O Ciclo Infodive', 'Como entregamos valor', 'Da descoberta à sustentação.',
  '[{"titulo":"Descoberta","descricao":"Entendimento do desafio.","icone":"search","ordem":1},{"titulo":"Implementação","descricao":"Deploy das soluções.","icone":"wrench","ordem":2},{"titulo":"Sustentação","descricao":"Operação contínua.","icone":"headphones","ordem":3}]'::jsonb, now()
WHERE NOT EXISTS (SELECT 1 FROM servicos_etapas);

INSERT INTO servicos_metodologia (id, eyebrow, headline, paragrafo, metricas, pilares, updated_at)
SELECT gen_random_uuid(), 'Como trabalhamos', 'Metodologia comprovada', 'Processos maduros e mensuráveis.',
  '[{"prefixo":"+","valor":500,"sufixo":"","label":"Projetos entregues"},{"prefixo":"","valor":99,"sufixo":"%","label":"Satisfação"}]'::jsonb,
  '[{"icone":"target","titulo":"Foco no resultado","descricao":"Entregamos o que importa."},{"icone":"users","titulo":"Time dedicado","descricao":"Especialistas por projeto."}]'::jsonb, now()
WHERE NOT EXISTS (SELECT 1 FROM servicos_metodologia);

INSERT INTO sobre_numeros (id, texto_descritivo, stats, updated_at)
SELECT gen_random_uuid(), 'Números que mostram nossa trajetória.',
  '[{"prefixo":"+","valor":20,"valorInicial":0,"sufixo":"","label":"Anos de mercado","coluna":"esquerda"},{"prefixo":"+","valor":500,"valorInicial":0,"sufixo":"","label":"Clientes atendidos","coluna":"direita"}]'::jsonb, now()
WHERE NOT EXISTS (SELECT 1 FROM sobre_numeros);

INSERT INTO sobre_timeline (id, eyebrow, headline, marcos, updated_at)
SELECT gen_random_uuid(), 'Nossa história', 'Linha do tempo',
  '[{"ano":"2003","titulo":"Fundação","descricao":"Início em Porto Alegre.","destaque":true,"ordem":1},{"ano":"2015","titulo":"Expansão nacional","descricao":"Atendimento em todo o Brasil.","destaque":false,"ordem":2}]'::jsonb, now()
WHERE NOT EXISTS (SELECT 1 FROM sobre_timeline);

INSERT INTO sobre_valores (id, eyebrow, headline, paragrafo, valores, updated_at)
SELECT gen_random_uuid(), 'Valores', 'O que nos move', 'Princípios que guiam nossa atuação.',
  '[{"icone":"shield","titulo":"Confiança","descricao":"Relações de longo prazo."},{"icone":"zap","titulo":"Agilidade","descricao":"Resposta rápida e eficiente."}]'::jsonb, now()
WHERE NOT EXISTS (SELECT 1 FROM sobre_valores);

INSERT INTO sobre_cultura (id, eyebrow, headline, paragrafo, fotos, updated_at)
SELECT gen_random_uuid(), 'Cultura', 'Quem faz a Infodive', 'Pessoas no centro de tudo.',
  '[{"imagemUrl":"https://infodive.com.br/img/cultura/1.jpg","alt":"Equipe Infodive","ordem":1},{"imagemUrl":"https://infodive.com.br/img/cultura/2.jpg","alt":"Escritório","ordem":2}]'::jsonb, now()
WHERE NOT EXISTS (SELECT 1 FROM sobre_cultura);
